services:
  renderer:
    image: grafana/grafana-image-renderer:latest
    environment:
      ENABLE_METRICS: "false"
      LOG_LEVEL: warn
      BROWSER_MAX_HEIGHT: "15000"
      BROWSER_MAX_WIDTH: "3000"
    expose:
      - "8081"

  grafana:
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
    depends_on:
      - renderer
